apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: demo-app
  labels:
    app: auth-service
  annotations:
    kubernetes.io/change-cause: "First deployment with tag latest"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: pratikkumar54/auth-svc-demo:1.0.0
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /hello
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /hello
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: log-level
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: api-key