apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-service-hpa
  namespace: demo-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-service
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50