apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: demo-app
data:
  log-level: 'debug'
  DB_HOST: 'mongo-statefulset-0.mongo-headless-service.demo-app.svc.cluster.local,mongo-statefulset-1.mongo-headless-service.demo-app.svc.cluster.local:27017'
  DB_REPLICASET: 'rs0'
  DB_NAME: 'fans'