apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: demo-app
  labels:
    app: user-service
  annotations:
    kubernetes.io/change-cause: "Update the tag to 1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: pratikkumar54/user-svc-demo:1.0.0
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "156Mi"
        livenessProbe:
          httpGet:
            path: /hello
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /hello
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
          - name: LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: log-level
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_HOST
          - name: DB_REPLICASET
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_REPLICASET
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_NAME
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DB_USER
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DB_PASSWORD
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: api-key